import main_funcs.mixed.mysql_connection as mc 
db_pd = mc.engine.connect()
db_pd.execute("CREATE TABLE IF NOT EXISTS form_codes (form_code VARCHAR(50), test_type VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS schools (school_name VARCHAR(50),test_1 KEY (school_name),school_country VARCHAR(50),school_city VARCHAR(50),school_address VARCHAR(100),teacher_name VARCHAR(50),teacher_tel VARCHAR(50),teacher_mail VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS iopssablon (test_date VARCHAR(50),school VARCHAR(50),grade VARCHAR(50),country_code VARCHAR(50),lang_code VARCHAR(50),form_code VARCHAR(50),test_time VARCHAR(50),test_type VARCHAR(50), test_session VARCHAR(50),test_page VARCHAR(50),room VARCHAR(50),student_name VARCHAR(50),student_lastname VARCHAR(50),student_number VARCHAR(50),student_class VARCHAR(50),bmonth VARCHAR(50),bday VARCHAR(50),byear VARCHAR(50),gender VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS students (student_number VARCHAR(50),student_name VARCHAR(50),student_lastname VARCHAR(50),date_of_birth_d_m_y VARCHAR(50),gender VARCHAR(50),student_class VARCHAR(50),school VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS test_1speaking (country VARCHAR(50), provience VARCHAR(50), school VARCHAR(50), form_code VARCHAR(50), main_date VARCHAR(50), test_date VARCHAR(50), student_lastname VARCHAR(50), student_name VARCHAR(50), student_number VARCHAR(50), student_class VARCHAR(50), total_score VARCHAR(50), speaking_cefr VARCHAR(50), speaking_level VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS test_3_speaking (country VARCHAR(50), provience VARCHAR(50), school VARCHAR(50), form_code VARCHAR(50), main_date VARCHAR(50), test_date VARCHAR(50), student_lastname VARCHAR(50), student_name VARCHAR(50), student_number VARCHAR(50), student_class VARCHAR(50), total_score VARCHAR(50), speaking_cefr VARCHAR(50), speaking_level VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS test_1step_1 (country VARCHAR(50), provience VARCHAR(50), school VARCHAR(50), form_code VARCHAR(50), main_date VARCHAR(50), test_date VARCHAR(50), student_lastname VARCHAR(50), student_name VARCHAR(50), student_number VARCHAR(50), student_class VARCHAR(50), reading_stars VARCHAR(50), reading_score VARCHAR(50), reading_cefr VARCHAR(50), reading_lexile VARCHAR(50), listening_stars VARCHAR(50), listening_score VARCHAR(50), listening_cefr VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS test_1step_2 (country VARCHAR(50), provience VARCHAR(50), school VARCHAR(50), form_code VARCHAR(50), main_date VARCHAR(50), test_date VARCHAR(50), student_lastname VARCHAR(50), student_name VARCHAR(50), student_number VARCHAR(50), student_class VARCHAR(50), reading_stars VARCHAR(50), reading_score VARCHAR(50), reading_cefr VARCHAR(50), reading_lexile VARCHAR(50), listening_stars VARCHAR(50), listening_score VARCHAR(50), listening_cefr VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS test_3_standard (country VARCHAR(50), provience VARCHAR(50), school VARCHAR(50), form_code VARCHAR(50), main_date VARCHAR(50), test_date VARCHAR(50), student_lastname VARCHAR(50), student_name VARCHAR(50), student_number VARCHAR(50), student_class VARCHAR(50), listening_score VARCHAR(50), listening_cefr VARCHAR(50), lfm_score VARCHAR(50), lfm_cefr VARCHAR(50), reading_score VARCHAR(50), reading_cefr VARCHAR(50), reading_lexile VARCHAR(50), total_score VARCHAR(50), osl VARCHAR(50))")
db_pd.execute("CREATE TABLE IF NOT EXISTS test_4 (country VARCHAR(50), provience VARCHAR(50), school VARCHAR(50), form_code VARCHAR(50), main_date VARCHAR(50), test_date VARCHAR(50), student_lastname VARCHAR(50), student_name VARCHAR(50), student_number VARCHAR(50), student_class VARCHAR(50), listening_score VARCHAR(50), listening_cefr VARCHAR(50), swe_score VARCHAR(50), swe_cefr VARCHAR(50), reading_score VARCHAR(50), reading_cefr VARCHAR(50), total_score VARCHAR(50))")

db_pd.close()
